name: Release
on:
  push:
    branches:
      - master

jobs:
  release-on-push:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - id: release
        uses: dmitriyStoyanov/release-on-push-action@master
        with:
          bump_version_scheme: patch
      - name: Check tag Output
        run: echo "Got tag version ${{ steps.release.outputs.tag_name }}"
      - name: Check version Output
        run: echo "Got version ${{ steps.release.outputs.name }}"
